[tool.poetry]
name = "astrobase"
version = "0.1.0"
description = "Astrobase API Server"
authors = ["Anthony Corletti <anthony@astrobase.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = {extras = ["all"], version = "^0.63.0"}
gunicorn = "^20.0.4"
PyJWT = "^2.0.1"
passlib = "^1.7.4"
google-api-python-client = "^2.0.2"
uvicorn = "^0.13.3"
boto3 = "^1.17.22"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
flake8 = "^3.8.4"
black = "^20.8b1"
isort = "^5.8.0"
mypy = "^0.812"
autoflake = "^1.4"
coverage = "^5.5"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
