[tool.poetry]
name = "astrobase"
version = "0.1.0"
description = "Astrobase API Server"
authors = ["Anthony Corletti <anthcor@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
astro = "main:app"

[tool.poetry.dependencies]
python = "^3.9"
fastapi = {extras = ["all"], version = "^0.63.0"}
gunicorn = "^20.0.4"
PyJWT = "^2.0.1"
passlib = "^1.7.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = "^20.8b1"
uvicorn = "^0.13.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
